import { CharacterFactory } from '../systems/CharacterFactory.js';

export const GYM_UNCLE_DNA=Object.freeze({id:'gym_uncle',name:'Gym Uncle',role:'frontline',country:'global',visual:{icon:'🏋️',portrait:'assets/characters/gym_uncle_portrait.svg',battleSprite:'/assets/characters/gym_uncle_battle.svg',battleSpriteWidth:1.65,battleSpriteHeight:2.25,battleBarY:2.35,color:'#c75bff',accent:'#fff06a',modelType:'capsule',scale:1.22,silhouette:'Huge upper body, tiny legs, oversized dumbbell.',animationPersonality:'Top-heavy swagger, tiny rapid steps, dramatic recoil.'},stats:{cost:170,hp:340,attack:58,range:1.45,attackSpeed:.72,moveSpeed:.62,deployCD:5.8},combat:{attackType:'melee',special:'knockback',normalSkill:'Weight Smack',passive:'Armor Bully',hiddenSkill:'Manager Cannon',counterHooks:['armored','manager']},traits:['loud','armored_counter','protein_obsessed','top_heavy'],relationships:[{target:'manager',type:'hate',strength:.85},{target:'manager',type:'annoyance',strength:.95}],comedy:{failureBehavior:'Overcommits to a swing and launches the wrong thing.',comedyEvents:['manager_cannon','human_baseball','protein_rage'],rareBehaviorChance:.05,voice:'Booming confidence until tiny-leg physics intervenes.'}});
export const MANAGER_DNA=Object.freeze({id:'manager',name:'Manager',role:'support',country:'global',visual:{icon:'📊',color:'#4e78ff',accent:'#f7f7ff',modelType:'box',scale:1,silhouette:'Compact office silhouette with clipboard/tablet.',animationPersonality:'Tiny authoritative gestures and frantic pointing.'},stats:{cost:220,hp:150,attack:18,range:4.8,attackSpeed:.55,moveSpeed:.78,deployCD:8.5},combat:{attackType:'ranged',projectileSpeed:8.5,projectileColor:'#91b6ff',special:'support',normalSkill:'PowerPoint Attack',passive:'Annoyance Meter',hiddenSkill:'Emergency Meeting',counterHooks:['long_fight','gym_uncle']},traits:['support','non_frontline','annoying_authority','paperwork'],relationships:[{target:'gym_uncle',type:'annoyance',strength:.92}],comedy:{failureBehavior:'Issues an order at exactly the wrong moment.',comedyEvents:['emergency_meeting','powerpoint_attack','manager_cannon'],rareBehaviorChance:.045,voice:'Corporate certainty while everything burns.'}});
export const DRUNK_UNCLE_DNA=Object.freeze({id:'drunk_uncle',name:'Drunk Uncle',role:'bruiser',country:'vietnam',visual:{icon:'🍺',color:'#d88b35',accent:'#fff0a8',modelType:'capsule',scale:1.08,silhouette:'Round uncle, loose shirt, permanently suspicious beer mug.',animationPersonality:'Unsteady zigzag swagger, delayed punches, heroic wobble.'},stats:{cost:145,hp:285,attack:48,range:1.35,attackSpeed:.82,moveSpeed:.92,deployCD:5.2},combat:{attackType:'melee',special:'drunk',normalSkill:'Beer Punch',passive:'Liquid Courage',hiddenSkill:'Legendary Drunk',counterHooks:['swarm','kidnap']},traits:['drunk','bruiser','unpredictable'],relationships:[{target:'manager',type:'annoyance',strength:.65}],comedy:{failureBehavior:'May pass out at the worst possible moment and become enemy luggage.',comedyEvents:['beer_barrage','pass_out','enemy_kidnap','legendary_drunk'],rareBehaviorChance:.005,voice:'Loud philosophy with increasingly unreliable grammar.'}});

export const DR_DOPING_DNA=Object.freeze({id:'dr_doping',name:'Dr. Doping',role:'support',country:'global',visual:{icon:'💉',color:'#e8f7ff',accent:'#ff4f8b',modelType:'cylinder',scale:1,silhouette:'Thin doctor with absurdly oversized syringe and medical bag.',animationPersonality:'Precise tiptoe movement followed by alarmingly enthusiastic injections.'},stats:{cost:205,hp:165,attack:15,range:4.1,attackSpeed:.62,moveSpeed:.86,deployCD:7.6},combat:{attackType:'ranged',projectileSpeed:9,projectileColor:'#ff70a7',special:'support',normalSkill:'Boost Injection',passive:'Questionable Medicine',hiddenSkill:'Miracle Dose',counterHooks:['ally_buff','long_fight']},traits:['support','doctor','buff'],relationships:[{target:'drunk_uncle',type:'annoyance',strength:.45}],comedy:{failureBehavior:'15% chance to inject the wrong teammate and put them to sleep.',comedyEvents:['wrong_syringe','miracle_dose'],rareBehaviorChance:.15,voice:'Calm clinical confidence despite absolutely no consent forms.'}});

export const FISHERMAN_UNCLE_DNA=Object.freeze({id:'fisherman_uncle',name:'Fisherman Uncle',role:'counter',country:'vietnam',visual:{icon:'🎣',color:'#4ea5a1',accent:'#ffd66b',modelType:'capsule',scale:1.04,silhouette:'Lean fisherman with long rod, bucket and comically oversized hook.',animationPersonality:'Patient shuffle, sudden explosive hook cast, proud catch pose.'},stats:{cost:180,hp:220,attack:42,range:3.7,attackSpeed:.68,moveSpeed:.9,deployCD:6.4},combat:{attackType:'ranged',projectileSpeed:10,projectileColor:'#d9f5ff',special:'hook',normalSkill:'Hook Cast',passive:'Shark Sense',hiddenSkill:'SASHIMI',counterHooks:['shark','underground','animal']},traits:['counter','fisherman','anti_shark'],relationships:[{target:'shark_commando',type:'fear',strength:.35}],comedy:{failureBehavior:'Hooks scenery, props, or something that definitely was not dinner.',comedyEvents:['sashimi','wrong_catch'],rareBehaviorChance:.055,voice:'Quiet patience immediately replaced by seafood triumph.'}});

export const SUPERMARKET_AUNTIE_DNA=Object.freeze({id:'supermarket_auntie',name:'Supermarket Auntie',role:'ranged_swarm_control',country:'global',visual:{icon:'🛒',color:'#ef5c73',accent:'#8ee36b',modelType:'sphere',scale:1.03,silhouette:'Determined auntie with shopping bag overflowing with suspicious groceries.',animationPersonality:'Fast bargaining steps, furious throwing, handbag charge when empty.'},stats:{cost:130,hp:205,attack:31,range:3.25,attackSpeed:1.08,moveSpeed:1.08,deployCD:4.7},combat:{attackType:'ranged',projectileSpeed:8.8,projectileColor:'#ffdf70',special:'groceries',normalSkill:'Grocery Barrage',passive:'Clearance Hunter',hiddenSkill:'Shopping Bag Charge',counterHooks:['swarm','light_enemy']},traits:['ranged','swarm_control','auntie'],relationships:[{target:'drunk_uncle',type:'annoyance',strength:.58}],comedy:{failureBehavior:'Runs out of groceries and personally enters the argument with her shopping bag.',comedyEvents:['fish_throw','egg_throw','tomato_throw','onion_throw','bag_charge','enemy_kidnap'],rareBehaviorChance:.06,voice:'Every attack sounds like a price dispute she intends to win.'}});

export const CANONICAL_DNA=Object.freeze([GYM_UNCLE_DNA,MANAGER_DNA,DRUNK_UNCLE_DNA,DR_DOPING_DNA,FISHERMAN_UNCLE_DNA,SUPERMARKET_AUNTIE_DNA]);
export const CANONICAL_UNITS=Object.freeze(CANONICAL_DNA.map(dna=>CharacterFactory.createRuntimeConfig(dna)));
