// Enemy definitions. Stats get scaled by stage multipliers at spawn time.
// special: null | 'split' | 'steal' | 'fly' | 'rush' | 'summon' | 'enrage' | 'aoe'

export const ENEMIES = [
  {
    id: 'angry_printer',
    name: 'Angry Printer',
    color: 0x666677,
    accent: 0x222222,
    modelType: 'box',
    hp: 180,
    attack: 22,
    range: 1.4,
    attackSpeed: 1.0,
    moveSpeed: 1.7,
    attackType: 'melee',
    special: null,
    reward: 18,
    scale: 0.95,
  },
  {
    id: 'spreadsheet_slime',
    name: 'Spreadsheet Slime',
    color: 0x44dd88,
    accent: 0x88ffaa,
    modelType: 'sphere',
    hp: 120,
    attack: 14,
    range: 1.3,
    attackSpeed: 1.1,
    moveSpeed: 1.4,
    attackType: 'melee',
    special: 'split',
    splitInto: 'spreadsheet_slime_small',
    splitCount: 2,
    reward: 14,
    scale: 1.0,
  },
  {
    id: 'spreadsheet_slime_small',
    name: 'Slime Bit',
    color: 0x66ee99,
    accent: 0xaaffcc,
    modelType: 'sphere',
    hp: 50,
    attack: 8,
    range: 1.0,
    attackSpeed: 1.2,
    moveSpeed: 1.9,
    attackType: 'melee',
    special: null,
    reward: 6,
    scale: 0.5,
    hidden: true,
  },
  {
    id: 'tax_goblin',
    name: 'Tax Goblin',
    color: 0x88aa44,
    accent: 0xffcc33,
    modelType: 'capsule',
    hp: 140,
    attack: 18,
    range: 1.4,
    attackSpeed: 1.0,
    moveSpeed: 2.2,
    attackType: 'melee',
    special: 'steal',
    stealAmount: 25,
    reward: 22,
    scale: 0.9,
  },
  {
    id: 'overwork_zombie',
    name: 'Overwork Zombie',
    color: 0x6677aa,
    accent: 0x222244,
    modelType: 'capsule',
    hp: 380,
    attack: 30,
    range: 1.5,
    attackSpeed: 0.8,
    moveSpeed: 0.9,
    attackType: 'melee',
    special: null,
    reward: 28,
    scale: 1.05,
  },
  {
    id: 'traffic_cone_soldier',
    name: 'Traffic Cone Soldier',
    color: 0xff7733,
    accent: 0xffffff,
    modelType: 'cone',
    hp: 200,
    attack: 24,
    range: 1.4,
    attackSpeed: 1.1,
    moveSpeed: 1.6,
    attackType: 'melee',
    special: null,
    reward: 20,
    scale: 0.95,
  },
  {
    id: 'spam_email_bat',
    name: 'Spam Email Bat',
    color: 0xaa44ff,
    accent: 0xddaaff,
    modelType: 'sphere',
    hp: 90,
    attack: 16,
    range: 1.2,
    attackSpeed: 1.3,
    moveSpeed: 2.6,
    attackType: 'melee',
    special: 'fly',
    flyHeight: 1.4,
    reward: 16,
    scale: 0.7,
  },
  {
    id: 'deadline_demon',
    name: 'Deadline Demon',
    color: 0xaa2233,
    accent: 0xff4466,
    modelType: 'cone',
    hp: 260,
    attack: 34,
    range: 5.0,
    attackSpeed: 0.9,
    moveSpeed: 1.5,
    attackType: 'ranged',
    special: null,
    projectileSpeed: 9,
    projectileColor: 0xff4466,
    reward: 32,
    scale: 1.0,
  },
];

export const BOSSES = [
  {
    id: 'mega_printer',
    name: 'Mega Printer',
    isBoss: true,
    color: 0x444455,
    accent: 0xffcc33,
    modelType: 'box',
    hp: 4200,
    attack: 70,
    range: 6.0,
    attackSpeed: 0.6,
    moveSpeed: 0.8,
    attackType: 'ranged',
    special: 'aoe',
    splashRadius: 2.6,
    projectileSpeed: 8,
    projectileColor: 0xffcc33,
    reward: 220,
    scale: 2.0,
    bossSpecial: 'paper_storm',
  },
  {
    id: 'tax_dragon',
    name: 'Tax Dragon',
    isBoss: true,
    color: 0x88aa44,
    accent: 0xffcc33,
    modelType: 'cone',
    hp: 5600,
    attack: 80,
    range: 1.8,
    attackSpeed: 0.9,
    moveSpeed: 1.1,
    attackType: 'melee',
    special: 'steal',
    stealAmount: 60,
    reward: 280,
    scale: 2.2,
    bossSpecial: 'tax_breath',
  },
  {
    id: 'deadline_demon_king',
    name: 'Deadline Demon King',
    isBoss: true,
    color: 0x661122,
    accent: 0xff4466,
    modelType: 'cone',
    hp: 7400,
    attack: 95,
    range: 6.0,
    attackSpeed: 0.8,
    moveSpeed: 1.2,
    attackType: 'ranged',
    special: 'summon',
    summonId: 'deadline_demon',
    summonCount: 2,
    summonInterval: 8.0,
    projectileSpeed: 10,
    projectileColor: 0xff4466,
    reward: 360,
    scale: 2.4,
    bossSpecial: 'summon_wave',
  },
  {
    id: 'algorithm_overlord',
    name: 'Algorithm Overlord',
    isBoss: true,
    color: 0x222266,
    accent: 0x66aaff,
    modelType: 'box',
    hp: 10000,
    attack: 110,
    range: 7.0,
    attackSpeed: 0.7,
    moveSpeed: 1.0,
    attackType: 'ranged',
    special: 'enrage',
    enrageAt: 0.4,
    enrageAtkMul: 1.6,
    enrageSpdMul: 1.4,
    projectileSpeed: 11,
    projectileColor: 0x66aaff,
    reward: 500,
    scale: 2.6,
    bossSpecial: 'algorithm_burst',
  },
];

export const ENEMY_MAP = Object.fromEntries(ENEMIES.map(e => [e.id, e]));
export const BOSS_MAP = Object.fromEntries(BOSSES.map(b => [b.id, b]));
