// Player-deployable units. All stats are base values; upgrades modify them at runtime.
// modelType: 'box' | 'capsule' | 'sphere' | 'cylinder' | 'cone'
// attackType: 'melee' | 'ranged'
// special: prototype values plus data-driven canonical character hooks
import { CANONICAL_UNITS } from './canonicalCharacters.js';

export const UNITS = [
  {
    id: 'office_cat',
    name: 'Office Cat',
    icon: '🐱',
    color: 0x88aaff,
    accent: 0xffffff,
    modelType: 'capsule',
    cost: 50,
    deployCD: 0.8,
    hp: 220,
    attack: 28,
    range: 1.3,
    attackSpeed: 1.0,
    moveSpeed: 2.0,
    attackType: 'melee',
    special: null,
    projectileSpeed: 0,
    scale: 0.9,
  },
  {
    id: 'rice_cooker_tank',
    name: 'Rice Cooker Tank',
    icon: '🍲',
    color: 0xcccccc,
    accent: 0xffcc66,
    modelType: 'cylinder',
    cost: 120,
    deployCD: 2.5,
    hp: 900,
    attack: 22,
    range: 1.6,
    attackSpeed: 0.7,
    moveSpeed: 0.9,
    attackType: 'melee',
    special: 'taunt',
    projectileSpeed: 0,
    scale: 1.2,
  },
  {
    id: 'karaoke_uncle',
    name: 'Karaoke Uncle',
    icon: '🎤',
    color: 0xff66bb,
    accent: 0xffeeaa,
    modelType: 'box',
    cost: 180,
    deployCD: 2.0,
    hp: 260,
    attack: 60,
    range: 7.0,
    attackSpeed: 0.8,
    moveSpeed: 1.3,
    attackType: 'ranged',
    special: null,
    projectileSpeed: 12,
    projectileColor: 0xff66bb,
    scale: 1.0,
  },
  {
    id: 'scooter_cat',
    name: 'Scooter Cat',
    icon: '🛵',
    color: 0xffaa33,
    accent: 0x222222,
    modelType: 'box',
    cost: 160,
    deployCD: 1.8,
    hp: 320,
    attack: 50,
    range: 1.4,
    attackSpeed: 1.4,
    moveSpeed: 3.4,
    attackType: 'melee',
    special: 'dash',
    projectileSpeed: 0,
    scale: 1.0,
  },
  {
    id: 'grandma_slipper',
    name: 'Grandma Slipper',
    icon: '🩴',
    color: 0xff9966,
    accent: 0x664422,
    modelType: 'sphere',
    cost: 140,
    deployCD: 1.6,
    hp: 200,
    attack: 32,
    range: 6.5,
    attackSpeed: 1.1,
    moveSpeed: 1.5,
    attackType: 'ranged',
    special: 'stun',
    projectileSpeed: 14,
    projectileColor: 0xff9966,
    scale: 0.9,
  },
  {
    id: 'sleepy_intern',
    name: 'Sleepy Intern',
    icon: '😴',
    color: 0x66ddaa,
    accent: 0x336699,
    modelType: 'capsule',
    cost: 70,
    deployCD: 1.0,
    hp: 140,
    attack: 18,
    range: 5.5,
    attackSpeed: 1.3,
    moveSpeed: 1.6,
    attackType: 'ranged',
    special: null,
    projectileSpeed: 10,
    projectileColor: 0xaaffcc,
    scale: 0.85,
  },
  {
    id: 'manager_cannon',
    name: 'Manager Cannon',
    icon: '📢',
    color: 0x4466aa,
    accent: 0xffdd66,
    modelType: 'cone',
    cost: 280,
    deployCD: 3.0,
    hp: 380,
    attack: 45,
    range: 6.0,
    attackSpeed: 0.6,
    moveSpeed: 1.1,
    attackType: 'ranged',
    special: 'splash',
    splashRadius: 2.2,
    projectileSpeed: 9,
    projectileColor: 0xffdd66,
    scale: 1.1,
  },
  {
    id: 'hotpot_monk',
    name: 'Hotpot Monk',
    icon: '🍲',
    color: 0xcc3333,
    accent: 0xffcc44,
    modelType: 'sphere',
    cost: 320,
    deployCD: 3.4,
    hp: 320,
    attack: 38,
    range: 5.5,
    attackSpeed: 0.7,
    moveSpeed: 1.2,
    attackType: 'ranged',
    special: 'burn',
    burnDamage: 18,
    projectileSpeed: 8,
    projectileColor: 0xff5533,
    scale: 1.0,
  },
  ...CANONICAL_UNITS,
];

export const UNIT_MAP = Object.fromEntries(UNITS.map(u => [u.id, u]));
